<?php

namespace app\models;

use yii\db\ActiveRecord;


class Task extends ActiveRecord
{
    public static function tableName()
    {
        return 'tasks';
    }

    public function rules()
    {
        return [
            [['title', 'description'
            ], 'string'],
            [['manager_id', 'status_id', 'type_id', 'level_id', 'client_id', 'available', 'updated_at', 'created_at'
            ], 'integer'],
        ];
    }

    public function getStatus()
    {
        return $this->hasOne(Status::class, ['id' => 'status_id']);
    }

    public function getLevel()
    {
        return $this->hasOne(Level::class, ['id' => 'level_id']);
    }

    public function getType()
    {
        return $this->hasOne(Type::class, ['id' => 'type_id']);
    }

    public function getClient()
    {
        return $this->hasOne(Client::class, ['id' => 'client_id']);
    }

    public function getTimeTracks()
    {
        return $this->hasOne(TimeTracks::class, ['task_id' => 'id']);
    }

    public function getComments()
    {
        return $this->hasMany(Comment::class, ['task_id' => 'id']);
    }

    public function beforeSave($insert)
    {
        $this->title = htmlspecialchars($this->title);
        $this->description = htmlspecialchars($this->description);

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}